goog.provide("com.ttProject.bit.Bit9");
goog.provide("com.ttProject.bit.Bit10");
goog.provide("com.ttProject.bit.Bit11");
goog.provide("com.ttProject.bit.Bit12");
goog.provide("com.ttProject.bit.Bit13");
goog.provide("com.ttProject.bit.Bit14");
goog.provide("com.ttProject.bit.Bit15");
goog.provide("com.ttProject.bit.Bit16");
goog.provide("com.ttProject.bit.Bit17");
goog.provide("com.ttProject.bit.Bit18");
goog.provide("com.ttProject.bit.Bit19");
goog.provide("com.ttProject.bit.Bit20");
goog.provide("com.ttProject.bit.Bit21");
goog.provide("com.ttProject.bit.Bit22");
goog.provide("com.ttProject.bit.Bit23");
goog.provide("com.ttProject.bit.Bit24");
goog.provide("com.ttProject.bit.Bit25");
goog.provide("com.ttProject.bit.Bit26");
goog.provide("com.ttProject.bit.Bit27");
goog.provide("com.ttProject.bit.Bit28");
goog.provide("com.ttProject.bit.Bit29");
goog.provide("com.ttProject.bit.Bit30");
goog.provide("com.ttProject.bit.Bit31");
goog.provide("com.ttProject.bit.Bit32");
goog.provide("com.ttProject.bit.Bit33");
goog.provide("com.ttProject.bit.Bit34");
goog.provide("com.ttProject.bit.Bit35");
goog.provide("com.ttProject.bit.Bit36");
goog.provide("com.ttProject.bit.Bit37");
goog.provide("com.ttProject.bit.Bit38");
goog.provide("com.ttProject.bit.Bit39");
goog.provide("com.ttProject.bit.Bit40");
goog.provide("com.ttProject.bit.Bit41");
goog.provide("com.ttProject.bit.Bit42");
goog.provide("com.ttProject.bit.Bit43");
goog.provide("com.ttProject.bit.Bit44");
goog.provide("com.ttProject.bit.Bit45");
goog.provide("com.ttProject.bit.Bit46");
goog.provide("com.ttProject.bit.Bit47");
goog.provide("com.ttProject.bit.Bit48");
goog.provide("com.ttProject.bit.Bit49");
goog.provide("com.ttProject.bit.Bit50");
goog.provide("com.ttProject.bit.Bit51");
goog.provide("com.ttProject.bit.Bit52");
goog.provide("com.ttProject.bit.Bit53");
goog.provide("com.ttProject.bit.Bit54");
goog.provide("com.ttProject.bit.Bit55");
goog.provide("com.ttProject.bit.Bit56");
goog.provide("com.ttProject.bit.Bit57");
goog.provide("com.ttProject.bit.Bit58");
goog.provide("com.ttProject.bit.Bit59");
goog.provide("com.ttProject.bit.Bit60");
goog.provide("com.ttProject.bit.Bit61");
goog.provide("com.ttProject.bit.Bit62");
goog.provide("com.ttProject.bit.Bit63");
goog.provide("com.ttProject.bit.Bit64");

goog.require("com.ttProject.bit.super.BitN");
goog.require("com.ttProject.bit.Bit1");
goog.require("com.ttProject.bit.Bit2");
goog.require("com.ttProject.bit.Bit3");
goog.require("com.ttProject.bit.Bit4");
goog.require("com.ttProject.bit.Bit5");
goog.require("com.ttProject.bit.Bit6");
goog.require("com.ttProject.bit.Bit7");
goog.require("com.ttProject.bit.Bit8");

var set = function(_this, val) {
	if(val != undefined) {
		_this.set(val);
	}
};
com.ttProject.bit.Bit9  = function(val) {goog.base(this, new com.ttProject.bit.Bit1(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit10 = function(val) {goog.base(this, new com.ttProject.bit.Bit2(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit11 = function(val) {goog.base(this, new com.ttProject.bit.Bit3(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit12 = function(val) {goog.base(this, new com.ttProject.bit.Bit4(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit13 = function(val) {goog.base(this, new com.ttProject.bit.Bit5(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit14 = function(val) {goog.base(this, new com.ttProject.bit.Bit6(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit15 = function(val) {goog.base(this, new com.ttProject.bit.Bit7(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit16 = function(val) {goog.base(this, new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit17 = function(val) {goog.base(this, new com.ttProject.bit.Bit1(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit18 = function(val) {goog.base(this, new com.ttProject.bit.Bit2(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit19 = function(val) {goog.base(this, new com.ttProject.bit.Bit3(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit20 = function(val) {goog.base(this, new com.ttProject.bit.Bit4(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit21 = function(val) {goog.base(this, new com.ttProject.bit.Bit5(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit22 = function(val) {goog.base(this, new com.ttProject.bit.Bit6(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit23 = function(val) {goog.base(this, new com.ttProject.bit.Bit7(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit24 = function(val) {goog.base(this, new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit25 = function(val) {goog.base(this, new com.ttProject.bit.Bit1(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit26 = function(val) {goog.base(this, new com.ttProject.bit.Bit2(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit27 = function(val) {goog.base(this, new com.ttProject.bit.Bit3(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit28 = function(val) {goog.base(this, new com.ttProject.bit.Bit4(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit29 = function(val) {goog.base(this, new com.ttProject.bit.Bit5(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit30 = function(val) {goog.base(this, new com.ttProject.bit.Bit6(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit31 = function(val) {goog.base(this, new com.ttProject.bit.Bit7(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit32 = function(val) {goog.base(this, new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit33 = function(val) {goog.base(this, new com.ttProject.bit.Bit1(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit34 = function(val) {goog.base(this, new com.ttProject.bit.Bit2(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit35 = function(val) {goog.base(this, new com.ttProject.bit.Bit3(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit36 = function(val) {goog.base(this, new com.ttProject.bit.Bit4(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit37 = function(val) {goog.base(this, new com.ttProject.bit.Bit5(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit38 = function(val) {goog.base(this, new com.ttProject.bit.Bit6(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit39 = function(val) {goog.base(this, new com.ttProject.bit.Bit7(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit40 = function(val) {goog.base(this, new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit41 = function(val) {goog.base(this, new com.ttProject.bit.Bit1(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit42 = function(val) {goog.base(this, new com.ttProject.bit.Bit2(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit43 = function(val) {goog.base(this, new com.ttProject.bit.Bit3(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit44 = function(val) {goog.base(this, new com.ttProject.bit.Bit4(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit45 = function(val) {goog.base(this, new com.ttProject.bit.Bit5(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit46 = function(val) {goog.base(this, new com.ttProject.bit.Bit6(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit47 = function(val) {goog.base(this, new com.ttProject.bit.Bit7(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit48 = function(val) {goog.base(this, new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit49 = function(val) {goog.base(this, new com.ttProject.bit.Bit1(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit50 = function(val) {goog.base(this, new com.ttProject.bit.Bit2(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit51 = function(val) {goog.base(this, new com.ttProject.bit.Bit3(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit52 = function(val) {goog.base(this, new com.ttProject.bit.Bit4(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit53 = function(val) {goog.base(this, new com.ttProject.bit.Bit5(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit54 = function(val) {goog.base(this, new com.ttProject.bit.Bit6(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit55 = function(val) {goog.base(this, new com.ttProject.bit.Bit7(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit56 = function(val) {goog.base(this, new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit57 = function(val) {goog.base(this, new com.ttProject.bit.Bit1(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit58 = function(val) {goog.base(this, new com.ttProject.bit.Bit2(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit59 = function(val) {goog.base(this, new com.ttProject.bit.Bit3(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit60 = function(val) {goog.base(this, new com.ttProject.bit.Bit4(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit61 = function(val) {goog.base(this, new com.ttProject.bit.Bit5(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit62 = function(val) {goog.base(this, new com.ttProject.bit.Bit6(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit63 = function(val) {goog.base(this, new com.ttProject.bit.Bit7(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
com.ttProject.bit.Bit64 = function(val) {goog.base(this, new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8(), new com.ttProject.bit.Bit8());if(val != undefined) {this.set(val);}};
goog.inherits(com.ttProject.bit.Bit9, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit10, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit11, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit12, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit13, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit14, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit15, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit16, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit17, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit18, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit19, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit20, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit21, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit22, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit23, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit24, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit25, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit26, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit27, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit28, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit29, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit30, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit31, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit32, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit33, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit34, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit35, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit36, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit37, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit38, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit39, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit40, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit41, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit42, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit43, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit44, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit45, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit46, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit47, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit48, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit49, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit50, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit51, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit52, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit53, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit54, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit55, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit56, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit57, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit58, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit59, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit60, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit61, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit62, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit63, com.ttProject.bit.super.BitN);
goog.inherits(com.ttProject.bit.Bit64, com.ttProject.bit.super.BitN);
