goog.provide("com.ttProject.bit.Bit9");
goog.provide("com.ttProject.bit.Bit10");
goog.provide("com.ttProject.bit.Bit11");
goog.provide("com.ttProject.bit.Bit12");
goog.provide("com.ttProject.bit.Bit13");
goog.provide("com.ttProject.bit.Bit14");
goog.provide("com.ttProject.bit.Bit15");
goog.provide("com.ttProject.bit.Bit16");
goog.provide("com.ttProject.bit.Bit17");
goog.provide("com.ttProject.bit.Bit18");
goog.provide("com.ttProject.bit.Bit19");
goog.provide("com.ttProject.bit.Bit20");
goog.provide("com.ttProject.bit.Bit21");
goog.provide("com.ttProject.bit.Bit22");
goog.provide("com.ttProject.bit.Bit23");
goog.provide("com.ttProject.bit.Bit24");
goog.provide("com.ttProject.bit.Bit25");
goog.provide("com.ttProject.bit.Bit26");
goog.provide("com.ttProject.bit.Bit27");
goog.provide("com.ttProject.bit.Bit28");
goog.provide("com.ttProject.bit.Bit29");
goog.provide("com.ttProject.bit.Bit30");
goog.provide("com.ttProject.bit.Bit31");
goog.provide("com.ttProject.bit.Bit32");
goog.provide("com.ttProject.bit.Bit33");
goog.provide("com.ttProject.bit.Bit34");
goog.provide("com.ttProject.bit.Bit35");
goog.provide("com.ttProject.bit.Bit36");
goog.provide("com.ttProject.bit.Bit37");
goog.provide("com.ttProject.bit.Bit38");
goog.provide("com.ttProject.bit.Bit39");
goog.provide("com.ttProject.bit.Bit40");
goog.provide("com.ttProject.bit.Bit41");
goog.provide("com.ttProject.bit.Bit42");
goog.provide("com.ttProject.bit.Bit43");
goog.provide("com.ttProject.bit.Bit44");
goog.provide("com.ttProject.bit.Bit45");
goog.provide("com.ttProject.bit.Bit46");
goog.provide("com.ttProject.bit.Bit47");
goog.provide("com.ttProject.bit.Bit48");
goog.provide("com.ttProject.bit.Bit49");
goog.provide("com.ttProject.bit.Bit50");
goog.provide("com.ttProject.bit.Bit51");
goog.provide("com.ttProject.bit.Bit52");
goog.provide("com.ttProject.bit.Bit53");
goog.provide("com.ttProject.bit.Bit54");
goog.provide("com.ttProject.bit.Bit55");
goog.provide("com.ttProject.bit.Bit56");
goog.provide("com.ttProject.bit.Bit57");
goog.provide("com.ttProject.bit.Bit58");
goog.provide("com.ttProject.bit.Bit59");
goog.provide("com.ttProject.bit.Bit60");
goog.provide("com.ttProject.bit.Bit61");
goog.provide("com.ttProject.bit.Bit62");
goog.provide("com.ttProject.bit.Bit63");
goog.provide("com.ttProject.bit.Bit64");

goog.require("com.ttProject.bit.super.BitN");
goog.require("com.ttProject.bit.Bit1");
goog.require("com.ttProject.bit.Bit2");
goog.require("com.ttProject.bit.Bit3");
goog.require("com.ttProject.bit.Bit4");
goog.require("com.ttProject.bit.Bit5");
goog.require("com.ttProject.bit.Bit6");
goog.require("com.ttProject.bit.Bit7");
goog.require("com.ttProject.bit.Bit8");

(function(path) {
	set = function(_this, val) {
		if(val != undefined) {
			goog.base(_this, "set", val);
		}
	};
	path.Bit9 = function(val)  {goog.base(this, new path.Bit1(), new path.Bit8());set(this, val);};
	path.Bit10 = function(val) {goog.base(this, new path.Bit2(), new path.Bit8());set(this, val);};
	path.Bit11 = function(val) {goog.base(this, new path.Bit3(), new path.Bit8());set(this, val);};
	path.Bit12 = function(val) {goog.base(this, new path.Bit4(), new path.Bit8());set(this, val);};
	path.Bit13 = function(val) {goog.base(this, new path.Bit5(), new path.Bit8());set(this, val);};
	path.Bit14 = function(val) {goog.base(this, new path.Bit6(), new path.Bit8());set(this, val);};
	path.Bit15 = function(val) {goog.base(this, new path.Bit7(), new path.Bit8());set(this, val);};
	path.Bit16 = function(val) {goog.base(this, new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit17 = function(val) {goog.base(this, new path.Bit1(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit18 = function(val) {goog.base(this, new path.Bit2(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit19 = function(val) {goog.base(this, new path.Bit3(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit20 = function(val) {goog.base(this, new path.Bit4(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit21 = function(val) {goog.base(this, new path.Bit5(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit22 = function(val) {goog.base(this, new path.Bit6(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit23 = function(val) {goog.base(this, new path.Bit7(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit24 = function(val) {goog.base(this, new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit25 = function(val) {goog.base(this, new path.Bit1(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit26 = function(val) {goog.base(this, new path.Bit2(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit27 = function(val) {goog.base(this, new path.Bit3(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit28 = function(val) {goog.base(this, new path.Bit4(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit29 = function(val) {goog.base(this, new path.Bit5(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit30 = function(val) {goog.base(this, new path.Bit6(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit31 = function(val) {goog.base(this, new path.Bit7(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit32 = function(val) {goog.base(this, new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit33 = function(val) {goog.base(this, new path.Bit1(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit34 = function(val) {goog.base(this, new path.Bit2(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit35 = function(val) {goog.base(this, new path.Bit3(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit36 = function(val) {goog.base(this, new path.Bit4(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit37 = function(val) {goog.base(this, new path.Bit5(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit38 = function(val) {goog.base(this, new path.Bit6(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit39 = function(val) {goog.base(this, new path.Bit7(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit40 = function(val) {goog.base(this, new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit41 = function(val) {goog.base(this, new path.Bit1(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit42 = function(val) {goog.base(this, new path.Bit2(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit43 = function(val) {goog.base(this, new path.Bit3(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit44 = function(val) {goog.base(this, new path.Bit4(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit45 = function(val) {goog.base(this, new path.Bit5(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit46 = function(val) {goog.base(this, new path.Bit6(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit47 = function(val) {goog.base(this, new path.Bit7(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit48 = function(val) {goog.base(this, new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit49 = function(val) {goog.base(this, new path.Bit1(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit50 = function(val) {goog.base(this, new path.Bit2(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit51 = function(val) {goog.base(this, new path.Bit3(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit52 = function(val) {goog.base(this, new path.Bit4(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit53 = function(val) {goog.base(this, new path.Bit5(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit54 = function(val) {goog.base(this, new path.Bit6(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit55 = function(val) {goog.base(this, new path.Bit7(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit56 = function(val) {goog.base(this, new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit57 = function(val) {goog.base(this, new path.Bit1(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit58 = function(val) {goog.base(this, new path.Bit2(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit59 = function(val) {goog.base(this, new path.Bit3(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit60 = function(val) {goog.base(this, new path.Bit4(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit61 = function(val) {goog.base(this, new path.Bit5(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit62 = function(val) {goog.base(this, new path.Bit6(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit63 = function(val) {goog.base(this, new path.Bit7(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	path.Bit64 = function(val) {goog.base(this, new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8(), new path.Bit8());set(this, val);};
	goog.inherits(path.Bit9, path.super.BitN);
	goog.inherits(path.Bit10, path.super.BitN);
	goog.inherits(path.Bit11, path.super.BitN);
	goog.inherits(path.Bit12, path.super.BitN);
	goog.inherits(path.Bit13, path.super.BitN);
	goog.inherits(path.Bit14, path.super.BitN);
	goog.inherits(path.Bit15, path.super.BitN);
	goog.inherits(path.Bit16, path.super.BitN);
	goog.inherits(path.Bit17, path.super.BitN);
	goog.inherits(path.Bit18, path.super.BitN);
	goog.inherits(path.Bit19, path.super.BitN);
	goog.inherits(path.Bit20, path.super.BitN);
	goog.inherits(path.Bit21, path.super.BitN);
	goog.inherits(path.Bit22, path.super.BitN);
	goog.inherits(path.Bit23, path.super.BitN);
	goog.inherits(path.Bit24, path.super.BitN);
	goog.inherits(path.Bit25, path.super.BitN);
	goog.inherits(path.Bit26, path.super.BitN);
	goog.inherits(path.Bit27, path.super.BitN);
	goog.inherits(path.Bit28, path.super.BitN);
	goog.inherits(path.Bit29, path.super.BitN);
	goog.inherits(path.Bit30, path.super.BitN);
	goog.inherits(path.Bit31, path.super.BitN);
	goog.inherits(path.Bit32, path.super.BitN);
	goog.inherits(path.Bit33, path.super.BitN);
	goog.inherits(path.Bit34, path.super.BitN);
	goog.inherits(path.Bit35, path.super.BitN);
	goog.inherits(path.Bit36, path.super.BitN);
	goog.inherits(path.Bit37, path.super.BitN);
	goog.inherits(path.Bit38, path.super.BitN);
	goog.inherits(path.Bit39, path.super.BitN);
	goog.inherits(path.Bit40, path.super.BitN);
	goog.inherits(path.Bit41, path.super.BitN);
	goog.inherits(path.Bit42, path.super.BitN);
	goog.inherits(path.Bit43, path.super.BitN);
	goog.inherits(path.Bit44, path.super.BitN);
	goog.inherits(path.Bit45, path.super.BitN);
	goog.inherits(path.Bit46, path.super.BitN);
	goog.inherits(path.Bit47, path.super.BitN);
	goog.inherits(path.Bit48, path.super.BitN);
	goog.inherits(path.Bit49, path.super.BitN);
	goog.inherits(path.Bit50, path.super.BitN);
	goog.inherits(path.Bit51, path.super.BitN);
	goog.inherits(path.Bit52, path.super.BitN);
	goog.inherits(path.Bit53, path.super.BitN);
	goog.inherits(path.Bit54, path.super.BitN);
	goog.inherits(path.Bit55, path.super.BitN);
	goog.inherits(path.Bit56, path.super.BitN);
	goog.inherits(path.Bit57, path.super.BitN);
	goog.inherits(path.Bit58, path.super.BitN);
	goog.inherits(path.Bit59, path.super.BitN);
	goog.inherits(path.Bit60, path.super.BitN);
	goog.inherits(path.Bit61, path.super.BitN);
	goog.inherits(path.Bit62, path.super.BitN);
	goog.inherits(path.Bit63, path.super.BitN);
	goog.inherits(path.Bit64, path.super.BitN);
})(com.ttProject.bit);
